#!/bin/bash
#
#data de criação: 04/12/2023
#feitor por Renan Santos
#CVS $HEADER$

shopt -s -o nounset


email() {
xMail="continuar"
    while [ "xMail" == "continuar"]; do
        echo "/-/-/-/Bem Vindo ao Menu de Servidor E-Mail/-/-/-/"
        echo "[1 - Instalação do servidor Postfix (Email)]"
        echo "[2 - Desinstalar Servidor Postfix]"
        echo "[3 - Iniciar Servidor Postfix]"
        echo "[4 - Parar Servidor Postfix]"
        echo "[5 - Reniciar Servidor Postfix]"
        echo "[6 - Status do Servidor Postfix]"
        echo "[7 - Configurar o Servidor Postfix]"
        echo "[8 - Criar um dominio DNS para o Postfix]"
        echo "[9 - Adicionar Usuario]"
        echo "[10 -  Sair do Script]"
        read -p "Escolha uma Resposta: " choice

        case $choice in

        1)
        if ! command -v postfix, then
            echo "Servidor Não instalado"
            echo "Inciando Instalação..."
            apt-get install postfix -y
            sleep 2
            clear
            echo "Postfix Instalado comm Sucesso!!!"
        else
            echo "Servidor Ja instalado..."
            sleep 1
        fi
        
        if ! command -v mailutils; then
            echo "Mailutils não está instalado..."
            echo "Iniciando instalação"
            apt-get install mailutils -y
            sleep 2
            clear 
            echo "Mailutils instalado com sucesso"
        else
            echo "Mailutils ja esta instalado"

        fi
        ;;
        2)
            echo "Desinstalado Servidor..."
            apt-get purge postfiix -y
            sleep 2
            clear
            echo "Servidor Desinstalado com Sucesso"
        ;;

        3)
            echo "Iniciando Servidor..."
            systemctl start postfix
            sleep 2
            echo "Servidor Iniciado com sucesso"
        ;;
        4)
            echo "Parando Servidor..."
            systemctl stop postfix
            sleep 2
            clear
            echo "Servidor fora de funcionamento"
        ;;
        5)
            echo "Reniciando Servidor..."
            systemctl restart postfix
            sleep 2
            clear
            echo "Servidor Reniciado com Sucesso!!!"
        ;;
        6)
            systemctl status postfix
        ;;
        7)
            sudo dpkg-reconfigure postfix
            sleep 3
            clear
            echo "Servidor Reinicado com Sucesso!!!"
        ;;
        8)
        while [[ loop==true ]]; do
	echo "Zona que deseja colocar:*"
	read zone
	echo "Final da zona que deseja colocar:* (.local, .com, ...)"
	read end
	# Configurando zona no named.conf.default-zones
	zona_completa="$zone$end"
	zona_local="$dir_dns/db.$zone"
	{
		echo "zone @" {
		echo "      type master;"
		echo "      file =;"
		echo -e "};\n"

		sed -i 's/@/"x"/g' $conf_default
		sed -i "s|x|$zona_completa|g" $conf_default
		sed -i 's/=/"+"/g' $conf_default
		sed -i "s|+|$zona_local|g" $conf_default

	} >>"$conf_default"

	echo "Início da zona que seja colocar:* (www, ns1, ...)"
	read start
	echo "Ip do serviço associado a esse início da zona:* "
	read ip_service

	# Criando db. e configurando
	localhost="ns1.$zone"
	touch "$zona_local"
	{
		echo -e "; BIND reverse data file for empty rfc1918 zone\n;\n; DO NOT EDIT THIS FILE - it is used for multiple zones.\n; Instead, copy it, edit named.conf, and use that copy.\n;\n=TTL	86400\n@	IN	SOA	localhost. root.localhost. (\n			      1		; Serial\n			 604800		; Refresh\n			  86400		; Retry\n			2419200		; Expire\n			  86400 )	; Negative Cache TTL\n;\n@	IN	NS	localhost."
		echo "$start	IN	A	$ip_service"
		sed -i "s|=|$|" "$dir_dns/db.$zone"
		sed -i "s|localhost|$localhost|g" "$dir_dns/db.$zone"
	} >>"$dir_dns/db.$zone"

	echo "Deseja adicionar mais um início de zona? (S / N)"
	read verificar
	while [[ "$verificar" == "S" || "$verificar" == "s" ]]; do
		echo "Início da zona que seja colocar:* (www, ns1, ...)"
		read start
		echo "Ip do serviço associado a esse início da zona:* "
		read ip_service
		{
			echo "$start	IN	A	$ip_service"
		} >>"$dir_dns/db.$zone"

		echo "Deseja adicionar mais um início de zona? (S / N)"
		read verificar
	done

	echo "Deseja adicionar mais uma zona? (S / N)"
	read verificar
	if [[ "$verificar" == "N" || "$verificar" == "n" ]]; then
		break
	fi
done

# Configurando o resolv.conf
if [[ ! "$ip_fixo" == "0" ]]; then
	rm "/etc/resolv.conf"
	touch "/etc/resolv.conf"
	{
		echo "nameserver $ip_fixo"
	} >>"/etc/resolv.conf"
fi

echo "----------------------------------------------------------------------"
echo "Configuração realizada com sucesso!!!"
        ;;
        9)
            echo "Digite o nome do usuario que deseja: "
            read -r usuario

        sudo adduser $usuario

        sleep 2

        echo "Usuario adicionado com sucesso"
        ;;
        10)
        xMail="false"
        ;;
        *)
            echo "Opção Invalida. Escolha uma opção valida!!!"

        esac
    done

}
# Atualizar o sistema
while true; do
    echo "Deseja atualizar a máquina? (Digite 'S' ou 'N')"
    read resposta

    if [ "$resposta" == "S" ] || [ "$resposta" == "s" ]; then
        echo "Atualizando a máquina..."
        apt-get update -y && apt-get upgrade -y
        echo "Máquina atualizada com sucesso!"
        break # Sai do loop após uma resposta válida
    elif [ "$resposta" == "N" ] || [ "$resposta" == "n" ]; then
        echo "Você optou por não atualizar a máquina."
        break # Sai do loop após uma resposta válida
    else
        echo "Resposta inválida. Por favor, digite 'S' ou 'N'."
    fi
done

#chamar menu
email